server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Fallback para o React Router lidar com rotas diretas / F5
        try_files $uri $uri/ /index.html;
    }
}
